title: Brandon Riley
markdown: kramdown
destination: brandon-riley
permalink: pretty
baseurl: /brandon-riley
sass:
  sass_dir:          _scss
  style:            :compressed

exclude: [.sass-cache, package.json, Gruntfile.js, node_modules, README.md]